name: Mobile CI

on:
  push:
  pull_request:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json
      - name: Install deps
        working-directory: mobile
        run: npm ci
      - name: Typecheck
        working-directory: mobile
        run: npm run typecheck
      - name: Lint
        working-directory: mobile
        run: npm run lint
